//
// Created by Mason on 2025/1/5.
//

#ifndef BATMANINFER_BI_CPU_GEMM_ASSEMBLY_WRAPPER_HPP
#define BATMANINFER_BI_CPU_GEMM_ASSEMBLY_WRAPPER_HPP


#endif //BATMANINFER_BI_CPU_GEMM_ASSEMBLY_WRAPPER_HPP
