//
// Created by holynova on 2025/1/16.
//

#include "runtime/neon/functions/bi_ne_normalization_layer.hpp"
#include "runtime/neon/functions/bi_ne_mat_mul.hpp"
#include "runtime/neon/functions/BINEFeedForwardLayer.hpp"
#include "runtime/neon/functions/bi_ne_gemm.hpp"
#include "runtime/neon/functions/bi_ne_gemm_lowp_matrix_mul_core.hpp"
#include "runtime/neon/functions/bi_ne_reshape_layer.hpp"
#include "runtime/neon/functions/bi_ne_slice.hpp"
#include "runtime/neon/functions/bi_ne_split.hpp"
#include "runtime/neon/functions/bi_ne_transpose.hpp"
#include "runtime/neon/functions/bi_ne_reverse.h"
#include "runtime/neon/functions/bi_NEActivationLayer.h"
#include "runtime/neon/functions/bi_NEBatchNormalizationLayer.h"
#include "runtime/neon/functions/bi_NEChannelShuffleLayer.h"
#include "runtime/neon/functions/bi_NEConvolutionLayer.h"
#include "runtime/neon/functions/bi_NEGEMMConvolutionLayer.h"
#include "runtime/neon/functions/bi_NEDirectConvolutionLayer.h"
#include "runtime/neon/functions/bi_NEWinogradConvolutionLayer.h"
#include "runtime/neon/functions/bi_NEDepthToSpaceLayer.h"
#include "runtime/neon/functions/bi_NEDeconvolutionLayer.h"
#include "runtime/neon/functions/bi_NEConcatenateLayer.h"
#include "runtime/neon/functions/bi_NEDepthwiseConvolutionLayer.h"
#include "runtime/neon/functions/bi_NEDequantizationLayer.h"
#include "runtime/neon/functions/bi_NEArithmeticAddition.h"
#include "runtime/neon/functions/bi_NEArithmeticSubtraction.h"
#include "runtime/neon/functions/ne_pixel_wise_multiplication.hpp"
#include "runtime/neon/functions/bi_ne_elementwise_operations.hpp"
#include "runtime/neon/functions/bi_NEFlattenLayer.h"
#include "runtime/neon/functions/bi_NEFullyConnectedLayer.h"
#include "runtime/neon/functions/bi_NEQuantizationLayer.h"
#include "runtime/neon/functions/bi_NEPReluLayer.h"
#include "runtime/neon/functions/bi_ne_reshape_layer.hpp"
#include "runtime/neon/functions/bi_NEScale.h"
#include "runtime/neon/functions/bi_NESoftmaxLayer.h"
#include "runtime/neon/functions/bi_ne_rnn_layer.hpp"
#include "runtime/neon/functions/BINEAttentionLayer.hpp"
#include "runtime/neon/functions/bi_ne_slice.hpp"
#include "runtime/neon/functions/bi_ne_gemm_lowp_output_stage.hpp"
#include <runtime/neon/functions/BINEAttentionLowpLayer.hpp>
#include "runtime/neon/functions/BINERMSNormLayer.hpp"
#include <runtime/neon/functions/BINEGather.hpp>
#include <runtime/neon/functions/BINESelect.hpp>
#include <runtime/neon/functions/BINEMLPLayer.hpp>
#include <runtime/neon/functions/BINEArgMinMaxLayer.hpp>
#include <runtime/neon/functions/BINELayerNormLayer.hpp>
#include <runtime/neon/functions/BINEIntentGPTBlock.hpp>
#include <runtime/neon/functions/BINEMultiGPTBlock.hpp>